import Head from "next/head";
import Image from "next/image";
import AboutSection from "../components/about-section";
import CTASection from "../components/cta-section";
import ExperienceSection from "../components/experience-section";
import Header from "../components/common/Header/header";
import ProjectSection from "../components/project-section";
import ResumeModal from "../components/resume-modal";
import ContactSection from "../components/contact-section";
import Footer from "../components/common/Footer/footer";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="">
        <CTASection />
        <AboutSection />
        <ExperienceSection />
        <ProjectSection />
        <ContactSection />
      </main>
      <ResumeModal />
      <Footer />
    </div>
  );
}
